version: 2
jobs:
  macOS_swift_4.2:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Build
          command: swift build
      - run:
          name: Test
          command: swift test
      - run:
          name: Build Spec Fixtures
          command: ./build_specs.sh
  macOS_swift_5.0:
    macos:
      xcode: "10.2.0"
    steps:
      - checkout
      - run:
          name: Build
          command: swift build
      - run:
          name: Test
          command: swift test
      - run:
          name: Build Spec Fixtures
          command: ./build_specs.sh
workflows:
  version: 2
  workflow:
    jobs:
      - macOS_swift_4.2
      - macOS_swift_5.0
